version: "3.8"

services:
    apache2:
        image: 'php:7.4-apache'
        container_name: php
        restart: always
        ports:
           - 8787:80
        volumes:
            - ./:/var/www/html
